/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class FrameFrontPage extends javax.swing.JFrame {
    private AntrianLogic antrian = new AntrianLogic();

    
    /**
     * Creates new form FrameLogin
     */
    public FrameFrontPage() {
        initComponents();
    } 
    private void fileWriter() {
        try (java.io.BufferedWriter writer = new java.io.BufferedWriter(new java.io.FileWriter("antrian_kasir.txt"))) {
            for (Pesanan p : antrian.getSemua()) {
                String baris = p.getId() + "|" + p.getNama() + "|" + p.getPesananSebagaiString();
                writer.write(baris);
                writer.newLine();
            }
        } 
        catch (java.io.IOException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan ke file: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnTambahAntrian = new javax.swing.JButton();
        txtIDPesanan = new javax.swing.JTextField();
        txtNamaPelanggan = new javax.swing.JTextField();
        boxPesanan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelAntrian = new javax.swing.JTable();
        btnLayaniPesanan = new javax.swing.JButton();
        labelNextInLine = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Pelanggan:");

        jLabel2.setText("ID Pesanan:");

        jLabel3.setText("Pilih Pesanan:");

        btnTambahAntrian.setText("+ Tambah Ke Antrian");
        btnTambahAntrian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahAntrianActionPerformed(evt);
            }
        });

        boxPesanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Wagyu A5 Ribeye Steak", "Tomahawk Steak Dry-Aged 60 Days", "Filet Mignon with Truffle Butter", "Chateaubriand with Red Wine Reduction", "Kobe Beef Striploin with Himalayan Salt", "Dom Pérignon Vintage Champagne (Alcohol)", "Macallan 18 Years Double Cask Whisky (Alcohol)", "Negroni – Gin", "Vermouth", "Campari (Alcohol)", "Château Lafite Rothschild Red Wine (Alcohol)", "Espresso Martini – Vodka", "Coffee Liqueur (Alcohol)" }));
        boxPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxPesananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTambahAntrian, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boxPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(329, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTambahAntrian)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tabelAntrian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No. Antrian", "ID Pesanan", "Nama", "Pesanan"
            }
        ));
        jScrollPane1.setViewportView(tabelAntrian);

        btnLayaniPesanan.setText("Layani Pesanan");
        btnLayaniPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLayaniPesananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labelNextInLine, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLayaniPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLayaniPesanan)
                    .addComponent(labelNextInLine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void add2Table(){
        List<Pesanan> data = antrian.getSemua();
        String[] coloumn = {"No. Antrian", "ID Pesanan", "Nama", "Pesanan"};
        DefaultTableModel model = new DefaultTableModel(coloumn, 0);

        int no = 1;
        for (Pesanan p : data) {
            model.addRow(new Object[]{
                no++,
                p.getId(),
                p.getNama(),
                p.getPesananSebagaiString()
            });
        }
        tabelAntrian.setModel(model);
    }
    private void boxPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxPesananActionPerformed
        
    }//GEN-LAST:event_boxPesananActionPerformed

    private void btnTambahAntrianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahAntrianActionPerformed
        String id = txtIDPesanan.getText();
        String nama = txtNamaPelanggan.getText();
        String item = (String) boxPesanan.getSelectedItem();
        if(id.isEmpty() || nama.isBlank() || item.isBlank()){
            JOptionPane.showMessageDialog(this, "Isi seluruh data sebelum memasukkannya ke dalam antrian.", "Harap Ulangi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            Pesanan pesanan = new Pesanan(id, nama);
            pesanan.tambahPesanan(item);
            antrian.tambahPesanan(pesanan);
            add2Table();
            fileWriter();
            txtIDPesanan.setText("");
            txtNamaPelanggan.setText("");
        }
    }//GEN-LAST:event_btnTambahAntrianActionPerformed

    private void btnLayaniPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLayaniPesananActionPerformed
        if(antrian.antrianKosong()){
            labelNextInLine.setText("Kosong");
            JOptionPane.showMessageDialog(this, "Antrian Kosong", "Isi Antrian Terlebih Dahulu", JOptionPane.ERROR_MESSAGE);
        }
        Pesanan pesanan = antrian.layaniPesanan();
        labelNextInLine.setText("Sedang Melayani: " + pesanan.getNama());
        add2Table();
    }//GEN-LAST:event_btnLayaniPesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameFrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameFrontPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxPesanan;
    private javax.swing.JButton btnLayaniPesanan;
    private javax.swing.JButton btnTambahAntrian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelNextInLine;
    private javax.swing.JTable tabelAntrian;
    private javax.swing.JTextField txtIDPesanan;
    private javax.swing.JTextField txtNamaPelanggan;
    // End of variables declaration//GEN-END:variables
}
